// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

::uniffi::setup_scaffolding!("test");

// Export info about this UDL file
// See `uniffi_bindgen::macro_metadata` for how this is used.

const UNIFFI_META_CONST_UDL_TEST: ::uniffi::MetadataBuffer =
    ::uniffi::MetadataBuffer::from_code(::uniffi::metadata::codes::UDL_FILE)
        .concat_str("eq_swift")
        .concat_str("test")
        .concat_str("test");

#[doc(hidden)]
#[unsafe(no_mangle)]
pub static UNIFFI_META_UDL_TEST: [u8; UNIFFI_META_CONST_UDL_TEST.size] =
    UNIFFI_META_CONST_UDL_TEST.into_array();

// Record definitions, implemented as method-less structs, corresponding to `dictionary` objects.

// Top level functions, corresponding to UDL `namespace` functions.

// Object definitions, corresponding to UDL `interface` definitions.

// Callback Interface definitions, corresponding to UDL `callback interface` definitions.

// Export scaffolding checksums for UDL items
